### ISSUE TITLE
Cannnot configure Authenticator types with Keycloak 23.0.6

### ISSUE THREAD

**Issue by cride83** [wouterh-dev/keycloak-spi-trusted-device#6]
Hi

Keycloak version: 23.0.6
Postgres version: 14

I tried taking into use your extension for remembering MFA device in the login flow when user
has requirement to "Configure OTP".

Unfortunately I cannot configure the "Authenticator types" when editing the condition "Credential Configured".
When I try to use the flow I see that there is an error in the keycloak docker logs:

2024-05-08 05:08:25,595 WARN  [org.keycloak.services] (executor-thread-16) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1262)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1335)
	at nl.wouterh.keycloak.trusteddevice.authenticator.CredentialConfiguredCondition.matchCondition(CredentialConfiguredCondition.java:25)
	at org.keycloak.authentication.DefaultAuthenticationFlow.conditionalNotMatched(DefaultAuthenticationFlow.java:358)

The configuration dialog for Credential Configured looks like this:

![image](https://github.com/wouterh-dev/keycloak-spi-trusted-device/assets/9015991/28a857cb-d8f2-4ad7-8642-9c5c4b26ab4e)

The flow that I have tried to configured looks like this:

![image](https://github.com/wouterh-dev/keycloak-spi-trusted-device/assets/9015991/c006b4c0-ac39-4df5-aa18-53deda2b551a)

Is this a problem that the component is not yet supporting Keycloak 23.0.6 or have I missed something essential here?

**Comment by wouterh-dev** [comment]
This is a problem with Keycloak: https://github.com/keycloak/keycloak/issues/28979

The latest version will default to the "otp" authenticator type to work around this upstream bug: https://github.com/wouterh-dev/keycloak-spi-trusted-device/commit/4bd3603aaab4e183789a02bb11e098b4dc7faa73
